// Generated by CoffeeScript 1.6.2
require('ember');

module.exports = Em.Mixin.create({
  init: function() {
    var height, that, thumb, url, width;

    that = this;
    width = this.get('width');
    height = this.get('height');
    url = this.get('url');
    thumb = require('thumb');
    thumb(url, width, height, function(err, img, datauri) {
      var compile;

      compile = Em.Handlebars.compile;
      return that.$().html(img);
    });
    return this._super();
  }
});
